server:
  port: 8082
spring:
  application:
    name: logging-service
  cloud:
    nacos:
      server-addr: 192.168.150.129:8848
  rabbitmq:
    host: 192.168.150.129
    port: 5672
    username: root
    password: 123321
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/log_db?useSSL=false&serverTimezone=UTC
    username: root
    password: '050126'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhx.userservice.entiey.pojo
  configuration:
    map-underscore-to-camel-case: true